### ISSUE TITLE
DOC-2-1: Adding acceptance test to user story acceptance criteria

### ISSUE THREAD

**Issue by NanoProd** [NanoProd/StackOverflowMock#100]
# Description
• An acceptance test was generated for every user story
• This acceptance test must be included within the acceptance criteria of the referenced user story

#Example
• Test-1-7 (#80)  is linked to User story #47 --> BKND-2: New User Verification Process
• The user story must be referenced in the description part of the acceptance test.
• Within the user story, the acceptance tests must be included in a section called "acceptance tests"
• This must be verified for all open test issues, as well as the closed ones. 

#Comment 
The suggested approach is to mark down all of the user stories in a table, and cross them off as they are completed

# Ideal Hours
1

**Comment by SamSDK** [comment]
Missing Acceptance Test for #41 @PhilCarPi , cant find it.

**Comment by SamSDK** [comment]
Missing acceptance test for #48

**Comment by SamSDK** [comment]
missing for #44 #46 #41 as well

**Comment by SamSDK** [comment]
> Missing acceptance test for #48

Completed

**Comment by SamSDK** [comment]
Completed #44 & #46

**Comment by SamSDK** [comment]
Completed #41
