### ISSUE TITLE
VOTE-2-1: Daily Voting Cap on Questions - Back End

### ISSUE THREAD

**Issue by PhilCarPi** [NanoProd/StackOverflowMock#67]
# User Story: #52

# Description
• A user may vote on a question a maximum of 10 times per day.
• The necessary code to validate this should be implemented in the relevant controller.
• The code should send a message back to be displayed to the user when the cap has been reached.
• The message should give the following information:
1) When the user will be able to vote again.
2) The user has reached his daily cap.

# Ideal Hours
5

# Comments
Dependency (successor): BKND-1 #32 #31
Dependency (concurrent): VOTE-2-2 #68

**Comment by NanoProd** [comment]
When implementing the daily voting cap, we have three options for the time when the user is allowed to vote again: 24 hours after his first vote in the time period, 24 hours after the maximum cap has been reached. Or I suggest we reset the number of votes at a specific time every day, such as 6:00 am. For example, at 6:00 am all users' quantity of votes will be set back to zero. 

What do you guys think? I think if two people agree with me I will implement this solution for both voting on answers and voting on questions.
