### ISSUE TITLE
Test-1-4: Acceptance Testing for voting on answers (CORE-2)

### ISSUE THREAD

**Issue by PhilCarPi** [NanoProd/StackOverflowMock#77]
# User Story: #73

# Description
• An acceptance test is to be developed for the user story #50 
• The following template is to be filled and added to the user story when completed:
<table>
    <thead>
        <tr>
            <th colspan=3>Test Case 1: question upvoted by user</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan=3>
                 <b>Pre-Condition:</b><br>
                 Latest version. User logged in.
            </td>
        </tr>
        <tr>
            <td><b>Steps:</b></td>
            <td><b>Expected Results</b></td>
            <td><b>Actual Results</b></td>
        </tr>
        <tr>
            <td><b>1.</b>User upvotes on answer</td>
            <td>The vote count is incremented by one on the question</td>
            <td>As expected</td>
        </tr>
        <tr>
            <td colspan=3>
                <b>Results:</b><br>
                [Pass/Fail] (TBD)
            </td>
        </tr>
    </tbody>
</table>

<table>
    <thead>
        <tr>
            <th colspan=3>Test Case 2: question downvoted by user</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan=3>
                 <b>Pre-Condition:</b><br>
                 Latest version. User logged in.
            </td>
        </tr>
        <tr>
            <td><b>Steps:</b></td>
            <td><b>Expected Results</b></td>
            <td><b>Actual Results</b></td>
        </tr>
        <tr>
            <td><b>1.</b>User downvotes question</td>
            <td>The vote is decremented by one on the question</td>
            <td>As expected</td>
        </tr>
        <tr>
            <td colspan=3>
                <b>Results:</b><br>
                [Pass/Fail] (TBD)
            </td>
        </tr>
    </tbody>
</table>

# Ideal Hours
1

# Comments

**Comment by SamSDK** [comment]
Complete
