### ISSUE TITLE
Test-1-10: Acceptance Testing for Asking Questions (GUI-1)

### ISSUE THREAD

**Issue by PhilCarPi** [NanoProd/StackOverflowMock#83]
# User Story: #73

# Description
• An acceptance test is to be developed for the user story #45 
• The following template is to be filled and added to the user story when completed:
<table>
    <thead>
        <tr>
            <th colspan=3>Test Case 1: User asks question</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan=3>
                 <b>Pre-Condition:</b><br>
                 Latest version. User logged in.
            </td>
        </tr>
        <tr>
            <td><b>Steps:</b></td>
            <td><b>Expected Results</b></td>
            <td><b>Actual Results</b></td>
        </tr>
        <tr>
            <td><b>1.</b>User writes question</td>
            <td>User is able to write a question in the correct field</td>
            <td>As expected</td>
        </tr>
        <tr>
            <td colspan=3>
                <b>Results:</b><br>
                [Pass/Fail] (TBD)
            </td>
        </tr>
    </tbody>
</table>

<table>
    <thead>
        <tr>
            <th colspan=3>Test Case 2: Question is posted</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan=3>
                 <b>Pre-Condition:</b><br>
                 Latest version. User logged in.
            </td>
        </tr>
        <tr>
            <td><b>Steps:</b></td>
            <td><b>Expected Results</b></td>
            <td><b>Actual Results</b></td>
        </tr>
        <tr>
            <td><b>1.</b>User submits question</td>
            <td>question is posted on top of the list of questions</td>
            <td>As expected</td>
        </tr>
        <tr>
            <td colspan=3>
                <b>Results:</b><br>
                [Pass/Fail] (TBD)
            </td>
        </tr>
    </tbody>
</table>

# Ideal Hours
1

# Comments

**Comment by SamSDK** [comment]
Complete
