### ISSUE TITLE
Test-1-12: Acceptance Testing for U-1 User Login Page - user tries to login

### ISSUE THREAD

**Issue by PhilCarPi** [NanoProd/StackOverflowMock#85]
# User Story: #73

# Description
• An acceptance test is to be developed for the user story #43 
• The following template is to be filled and added to the user story when completed:
<table>
    <thead>
        <tr>
            <th colspan=3>Test Case 1: User attempts to Login with valid username and valid password</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan=3>
                 <b>Pre-Condition:</b><br>
                 User has a registered account: valid username and password. User has clicked on the login button from the home page and is now at the login page.
            </td>
        </tr>
        <tr>
            <td><b>Steps:</b></td>
            <td><b>Expected Results</b></td>
            <td><b>Actual Results</b></td>
        </tr>
        <tr>
            <td><b>1.</b> User enters his username in the username text field.</td>
            <td>N/A</td>
            <td>N/A</td>
        </tr>
        <tr>
            <td><b>2.</b> User enters his password in the password text field.</td>
            <td>N/A</td>
            <td>N/A</td>
        </tr>
        <tr>
            <td><b>3.</b> Click on the Sign In button.</td>
            <td>
                The Question page is loaded. A flash is shown at the top of the page that tells the user that they have successfully signed in.
           </td>
            <td>As expected</td>
        </tr>
        <tr>
            <td colspan=3>
                <b>Results:</b><br>
                Pass
            </td>
        </tr>
    </tbody>
</table>

<table>
    <thead>
        <tr>
            <th colspan=3>Test Case 2: User Attempts to log in with a valid username and invalid password</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan=3>
                 <b>Pre-Condition:</b><br>
                 User has a registered account: valid username and password. User has clicked on the login button from the home page and is now at the login page.
            </td>
        </tr>
        <tr>
            <td><b>Steps:</b></td>
            <td><b>Expected Results</b></td>
            <td><b>Actual Results</b></td>
        </tr>
        <tr>
            <td><b>1.</b>Enters a valid username</td>
            <td>
                N/A
           </td>
            <td>N/A</td>
        </tr>
        <tr>
            <td><b>2.</b> Enter a password that is not the same as the registered password for the account</td>
            <td>
               N/A
           </td>
            <td>N/A</td>
        </tr>        
         <tr>
            <td><b>8.</b> Click on the Sign In button.</td>
            <td>
             A warning sign flashes and tells the user: Username and password are not match! Please try again
           </td>
            <td>As expected</td>
        </tr>
        <tr>
            <td colspan=3>
                <b>Results:</b><br>
                Pass
            </td>
        </tr>
    </tbody>
</table>

<table>
    <thead>
        <tr>
            <th colspan=3>Test Case 3: User Attempts to log in with an invalid username and invalid password</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan=3>
                 <b>Pre-Condition:</b><br>
                User has clicked on the login button from the home page and is now at the login page.
            </td>
        </tr>
        <tr>
            <td><b>Steps:</b></td>
            <td><b>Expected Results</b></td>
            <td><b>Actual Results</b></td>
        </tr>
        <tr>
            <td><b>1.</b>Enters an invalid username</td>
            <td>
                N/A
           </td>
            <td>N/A</td>
        </tr>
        <tr>
            <td><b>2.</b> Enters a password, the password does not match the account because invalid username was entered</td>
            <td>
               N/A
           </td>
            <td>N/A</td>
        </tr>        
         <tr>
            <td><b>8.</b> Click on the Sign In button.</td>
            <td>
             A warning sign flashes and tells the user: Username and password are not match! Please try again
           </td>
            <td>As expected</td>
        </tr>
        <tr>
            <td colspan=3>
                <b>Results:</b><br>
                Pass
            </td>
        </tr>
    </tbody>
</table>

<table>
    <thead>
        <tr>
            <th colspan=3>Test Case 4: User enters username but leaves password field empty</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan=3>
                 <b>Pre-Condition:</b><br>
                  User has clicked on the login button from the home page and is now at the login page.
            </td>
        </tr>
        <tr>
            <td><b>Steps:</b></td>
            <td><b>Expected Results</b></td>
            <td><b>Actual Results</b></td>
        </tr>
        <tr>
            <td><b>1.</b>Enters a username</td>
            <td>
                N/A
           </td>
            <td>N/A</td>
        </tr>
        <tr>
            <td><b>2.</b>Leaves password field blank</td>
            <td>
               N/A
           </td>
            <td>N/A</td>
        </tr>        
         <tr>
            <td><b>8.</b> Click on the Sign In button.</td>
            <td>
             A warning sign flashes over the password field and tells the user: Please fill out this field
           </td>
            <td>As expected</td>
        </tr>
        <tr>
            <td colspan=3>
                <b>Results:</b><br>
                Pass
            </td>
        </tr>
    </tbody>
</table>

<table>
    <thead>
        <tr>
            <th colspan=3>Test Case 5:User leaves username field blank</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan=3>
                 <b>Pre-Condition:</b><br>
                User has clicked on the login button from the home page and is now at the login page.
            </td>
        </tr>
        <tr>
            <td><b>Steps:</b></td>
            <td><b>Expected Results</b></td>
            <td><b>Actual Results</b></td>
        </tr>
        <tr>
            <td><b>1.</b>User does not enter a username</td>
            <td>
                N/A
           </td>
            <td>N/A</td>
        </tr>
        <tr>
            <td><b>2.</b> User does or does not enter a password</td>
            <td>
               N/A
           </td>
            <td>N/A</td>
        </tr>        
         <tr>
            <td><b>8.</b> Click on the Sign In button.</td>
            <td>
                A warning sign flashes over the Username field and tells the user: Please fill out this field
           </td>
            <td>As expected</td>
        </tr>
        <tr>
            <td colspan=3>
                <b>Results:</b><br>
                Pass
            </td>
        </tr>
    </tbody>
</table>

# Ideal Hours
1

# Comments

**Comment by NanoProd** [comment]
Acceptance tests have been added to user story.
